### ISSUE TITLE
Hi, we propse a large-scale dvs346 based single object tracking dataset, can you add it into this github?

### ISSUE THREAD

**Issue by wangxiao5791509** [uzh-rpg/event-based_vision_resources#132]
Paper: [https://arxiv.org/abs/2108.05015](https://arxiv.org/abs/2108.05015) 

Project: [https://sites.google.com/view/viseventtrack/](https://sites.google.com/view/viseventtrack/)

**Comment by guillermogb** [comment]
Dear @wangxiao5791509 could you edit the readme and create a pull request? 
See for example: https://github.com/uzh-rpg/event-based_vision_resources/pull/133 
Thanks.

**Comment by guillermogb** [comment]
@wangxiao5791509 Could you make the changes and create a pull request?

**Comment by guillermogb** [comment]
thanks
