### ISSUE TITLE
Added a new paper on MOD for event-based cameras

### ISSUE THREAD

**Issue by anindya2001** [uzh-rpg/event-based_vision_resources#135]
Hi, I have added my recent paper on '[Moving Object Detection for Event-based Vision using Graph Spectral Clustering](https://www.researchgate.net/publication/354462913_Moving_Object_Detection_for_Event-based_Vision_using_Graph_Spectral_Clustering)', accepted in the ICCVW 2021. I have created a pull request for the same.

**Comment by guillermogb** [comment]
Thanks. Already in master branch. No need to open an issue for this; the pull requests are enough.
For the actual entry, the formatting has been adapted to the convention (names, conference name, etc.) and there is no need to put the same link twice. You may change the link of the paper for the official, open access one, when the paper is accessible via the Computer Vision Foundation.
