### ISSUE TITLE
Link for 'Hillhouse Technology' is not correct

### ISSUE THREAD

**Issue by Rtakaha** [uzh-rpg/event-based_vision_resources#205]
Hi, When I clicked the link for [Hillhouse Technology](http://www.hillhouse-tech.com/) in 'Companies working on Event-based Vision', I reached to a blog that seems irrelevant to event-based cameras. (I know Japanese and the blog is for something very inappropriate... lol)

I believe that the domain for Hill house Technology has been expired and that domain has been taken by someone else.

I think it's better to be fixed. Thank you!

**Comment by guillermogb** [comment]
link removed. Thanks
