### ISSUE TITLE
Can you add N-EPIC-Kitchens (CVPR22)? 

### ISSUE THREAD

**Issue by EgocentricVision** [uzh-rpg/event-based_vision_resources#242]
Can you add this work? https://openaccess.thecvf.com/content/CVPR2022/html/Plizzari_E2GOMOTION_Motion_Augmented_Event_Stream_for_Egocentric_Action_Recognition_CVPR_2022_paper.html 

It is N-EPIC-Kitchens, the first event-based camera extension of the large-scale EPIC-Kitchens dataset.

**Comment by guillermogb** [comment]
Done; thanks. It would have been easier with a pull request.
@EgocentricVision, @plana93, @Chiaraplizz
Please feel free to add missing entries.
