### ISSUE TITLE
Isn't Visual Odometry just Ego-Motion? Why separate them?

### ISSUE THREAD

**Issue by DongHappyyy** [uzh-rpg/event-based_vision_resources#256]
My understanding is that the Visual Odometry is a Ego-Motion (also called Camera Motion).
Is there a misunderstanding in my understanding?

**Comment by guillermogb** [comment]
The SLAM (Simultaneous Localization And Mapping) section has several subsections, such as: 
- Localization, Ego-motion estimation -> estimate camera motion given a map of the scene.
- Visual Odometry -> no map is given. Both, scene map and motion are estimated concurrently.
- etc. 
This is what, I believe, is a common meaning for these subsection titles.

**Comment by DongHappyyy** [comment]
Can I understand that within the scope of SLAM, there is a difference between visual odometry and ego motion (map is given or not); If SLAM is not involved, then VO and ego motion are equivalent.

**Comment by guillermogb** [comment]
Maybe I am a bit relaxed about the exact meaning of these keywords. You would have to look them up more precisely in a glossary about computer vision or robotics. 
What's the concrete suggestion or question about the list in the repository?

**Comment by DongHappyyy** [comment]
I saw a sentence in the paper (Part I: The First 30 Years and Fundamentals) written by Professor Davide Scaramuzza: "Visual odometry (VO) is the process of estimating the egomotion of an agent (e.g., vehicle, human, and robot) using only the input of a single or multiple cameras attached to it.", so my understanding is that Visual Odometry and Ego motion are essentially the same thing, just with different names. 

 In another article titled "Deep learning based robust positioning for all weather autonomous driving", it was mentioned that "Ego motion estimation (also called odometry) with onboard sensors provides a complete localization solution in challenging environments, predicting the accurate relative self position of AVs." This further confirms my understanding.

I have no specific suggestions, on the contrary, I respect your summary deeply. I just see that you separated VO and ego motion, and I think my understanding is incorrect, so I want to communicate with you.

**Comment by guillermogb** [comment]
- Would you be satisfied if "Localization, Ego-motion estimation" was replaced by "Localization, pose estimation"? https://github.com/uzh-rpg/event-based_vision_resources/pull/258 ?
- What "summary" do you refer to? (the repository?)

**Comment by DongHappyyy** [comment]
It's good to keep it for now. To be honest, I didn't think of a particularly good classification method either. Pose estimation is not very appropriate either. As far as I know, there is still a gap between pose estimation (more used in SfM ) and motion estimation (more used in SLAM)

**Comment by guillermogb** [comment]
Alright. Then we can close this issue and delete the PR. These kind of discussions are usually communicated via e-mail, I think.
