### ISSUE TITLE
split simulators and datasets to two sections

### ISSUE THREAD

**Issue by tobidelbruck** [uzh-rpg/event-based_vision_resources#272]
Everything is there now but navigating to or linking to these two separate things is not possible now. Can I attempt to split them into two major sections?

**Comment by guillermogb** [comment]
Hi Tobi. 
We could create subsections in the table of content -toc- for ease of navigation (at the expense of a longer toc).
Currently the organization follows that in the TPAMI 2022 survey paper, section 6.2 "Datasets and simulators". Of course, we can split the content if needed. I feel like datasets and simulators were more connected at the beginning, when there was need of data and modeling. Maybe now they are more apart than before.

**Comment by guillermogb** [comment]
this was implemented some time ago. Closing. thank you.
