### ISSUE TITLE
How to get the timestamp with DVS240C connecting to FPGA？

### ISSUE THREAD

**Issue by hisrg** [uzh-rpg/event-based_vision_resources#72]
Hi，Please tell me how to get the timestamp with DVS240C connectting To FPGA by CAVIR cable？
this cable is 40 line. Please provide more detail information. thanks

**Comment by guillermogb** [comment]
I think you want to contact iniVation (the manufacturer of the DAVIS240C):
https://inivation.com/support/
and e-mail: support@iniVation.com
