### ISSUE TITLE
[Paper Wanted]: Event Cameras, from SLAM to High Speed Video

### ISSUE THREAD

**Issue by LarryDong** [uzh-rpg/event-based_vision_resources#88]
Hi, thanks for this nice resource list.

I'm look for Dr. Henri Rebecq's PhD dissertation, "Event Cameras, from SLAM to High Speed Video",
but cannot find this on "Dissertation" catalog or anywhere else.
So could you please provide a link to this?

Thanks so much.

**Comment by guillermogb** [comment]
Hi, Henri's thesis will eventually be available on [RPG's publication page](http://rpg.ifi.uzh.ch/publications.html), just like E. Mueggler's thesis.
The thesis is undergoing some final revision. You may contact the author for a copy. Best regards.

**Comment by guillermogb** [comment]
http://rpg.ifi.uzh.ch/docs/PhD19_Rebecq.pdf
